import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ShoppingBasket } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";

/**
 * The sans font is used for headings and body text
 */
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

/**
 * Like code, the mono font is used for text elements that are less important
 */
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
			>
				<SidebarProvider>
					<AppSidebar />
					<div className="px-8 w-dvw">
						<header className="flex h-20 items-center justify-between">
							<div className="flex items-center gap-x-4">
								<SidebarTrigger />
								<h1 className="text-4xl">
									<Link href="/">Recipes</Link>
								</h1>
							</div>
							<Button size="icon" asChild>
								<Link href="/shopping-cart">
									<ShoppingBasket />
								</Link>
							</Button>
						</header>
						{children}
					</div>
				</SidebarProvider>
				<Toaster />
			</body>
		</html>
	);
}
